### ISSUE TITLE
Issue 1 Search for CryptoCurrency

### ISSUE THREAD

**Issue by dcatan89** [dcatan89/CryptoDex#1]
## ⚙️ Feature 1 

> ##### Which feature is affected by this update?

User Can use the Searchbar to look up Cryptocurriencies
## 📐 Plan

> ##### Summary of the technical approach to be taken.

Start with the HTML and CSS to  mimic the wireframe, then check if the API works in populating the correct data. Afterwards work on the JavaScript search function to display correct data.
## 🖼️ Wireframes

<img width="789" alt="Screen Shot 2022-03-01 at 12 22 47 PM" src="https://user-images.githubusercontent.com/90487207/156243442-a576ba38-114c-4152-b6ef-f07a12499a79.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ...Add a Navbar with search Feature
- [x] ...Create the HTML and CSS for the Background Logo
- [x]  Make Sure that the box holding the content is transparent
- [x] Create the headers for the box content and dummy data so that styling is correct
- [x] Make Sure the data is correct for the box when applying API data
- [x] Make Sure that when typing in search bar the content box disappears
- [x]  When search is clicked, make sure the data is correct 
- [x] Make Sure the header and symbol ticker are the same when searched
- [x] -Make Sure media queries are working correctly 
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
