### ISSUE TITLE
Issue 2: User can add Crypto to a Watchlist

### ISSUE THREAD

**Issue by dcatan89** [dcatan89/CryptoDex#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add Certain Cryptos to their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The User will have the ability to add their favorite cryptos after searching to a watchlist
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="727" alt="Screen Shot 2022-03-07 at 11 13 23 AM" src="https://user-images.githubusercontent.com/90487207/157102046-141a8e09-d650-4c6e-9b18-1629605fc68f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... Make sure to  have  Add  to watch list button for searched crypto
- [x] Make sure that added to watchlist have the button showing added and a click event listener
- [x] See if the data is correct in the entries array
- [x] ...Make sure that the local storage saves the data
- [x] Make Sure it looks good in both mobile and desktop view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
