### ISSUE TITLE
Issue 3: User can View their Watchlist

### ISSUE THREAD

**Issue by dcatan89** [dcatan89/CryptoDex#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view their Watchlists

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks on their watchlists, they will be able to see an unordered list of their favorite coins and their data at certain time stamps

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="699" alt="Screen Shot 2022-03-07 at 4 10 49 PM" src="https://user-images.githubusercontent.com/90487207/157140933-4daabd42-d935-465e-ba17-f169722b8714.png">

<img width="472" alt="Screen Shot 2022-03-07 at 4 11 27 PM" src="https://user-images.githubusercontent.com/90487207/157140843-4a1b41a8-43b0-4fc9-88eb-0c88e5dcc48c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make sure to put dummy data that will help with CSS and HTML fitting
- [x] Make sure to add an anchor button for watchlists
- [x] Make sure to add a div with a new dataview for watchlist
- [x] Make sure to create a dom tree for the watchlist entries array
- [x] Make sure that the watchlist prepends it from the newest to oldest in the list
- [x] include a timestamp for each entry so that there is a visible showing of when it was bookmarked
- [x] add a view button so that it goes to current data
- [x] dataview should stay the same upon onloading
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
