### ISSUE TITLE
Issue 4: User can delete off their watchlist

### ISSUE THREAD

**Issue by dcatan89** [dcatan89/CryptoDex#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to delete entries from watchlist

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view the individual entries by clicking view, they will enter a new view. There will be a remove button that will open a modal and a back to watchlist button. Confirming removal will delete entry and cancelling will return the user back to the screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="356" alt="Screen Shot 2022-03-08 at 1 01 21 AM" src="https://user-images.githubusercontent.com/90487207/157203735-61ce03ee-0f49-4443-bbc9-e2453a074904.png">
<img width="360" alt="Screen Shot 2022-03-08 at 1 01 36 AM" src="https://user-images.githubusercontent.com/90487207/157203737-facdb29d-c2d4-46cf-bd46-e7e50082a61e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make sure to add click event listener to the view button 
- [x] Make sure new data view has correct values, data.added
- [x] Make sure to add a remove button and back to watchlist button
- [x] Make sure that the remove button opens modal
- [x] Confirming modal will delete entry, cancelling will remove modal
- [x] Make sure to add click event listener to back to watchlist button
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
