### ISSUE TITLE
Issue 5: User can Search for Trending Coins

### ISSUE THREAD

**Issue by dcatan89** [dcatan89/CryptoDex#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User Can View the top trending Coins
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the top Trending coins they will be able to see the ranking list of the top 25-50 cryptos
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [] Make sure API data is correct
- [x] Make sure to create a function that will hold the data
- [x] Make Sure there is a new domtree function for the top trending coins
- [x] Make Sure to append the data in descending order starting from 1
- [x] make sure there is a anchor tag for both mobile and desktop
- [x] make sure that the data is displayed correctly
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
